In [63]:
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
#Let's start with importing necessary libraries
from sklearn.preprocessing import StandardScaler 
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.model_selection import KFold
from statsmodels.stats.outliers_influence import variance_inflation_factor 
from sklearn.metrics import accuracy_score, confusion_matrix, roc_curve, roc_auc_score
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

In [64]:
data = pd.read_csv("nba_2013.csv") # Reading the Data
data.head()

,player,pos,age,bref_team_id,g,gs,mp,fg,fga,fg.,...,drb,trb,ast,stl,blk,tov,pf,pts,season,season_end
0,Quincy Acy,SF,23,TOT,63,0,847,66,141,0.468,...,144,216,28,23,26,30,122,171,2013-2014,2013
1,Steven Adams,C,20,OKC,81,20,1197,93,185,0.503,...,190,332,43,40,57,71,203,265,2013-2014,2013
2,Jeff Adrien,PF,27,TOT,53,12,961,143,275,0.520,...,204,306,38,24,36,39,108,362,2013-2014,2013
3,Arron Afflalo,SG,28,ORL,73,73,2552,464,1011,0.459,...,230,262,248,35,3,146,136,1330,2013-2014,2013
4,Alexis Ajinca,C,25,NOP,56,30,951,136,249,0.546,...,183,277,40,23,46,63,187,328,2013-2014,2013

In [74]:


original_headers = list(data.columns.values)

# "Position (pos)" is the class attribute we are predicting. 
class_column = 'pts'

feature_columns = ['fg','x3p','x2p','ft','orb','drb','ast','stl','blk','tov','pf']


# column selection to split the data into features and class.
nba_feature = data[feature_columns]
nba_class = data[class_column]

In [75]:
scalar = StandardScaler()
X_scaled = scalar.fit_transform(X)

H:\anaconda\lib\site-packages\sklearn\preprocessing\data.py:625: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
H:\anaconda\lib\site-packages\sklearn\base.py:462: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)

In [76]:
vif = pd.DataFrame()
vif["vif"] = [variance_inflation_factor(X_scaled,i) for i in range(X_scaled.shape[1])]
vif["Features"] = X.columns

#let's check the values
vif

           vif Features
0     7.808937        g
1     5.832825       gs
2    40.417809       mp
3    19.263473      fg.
4    22.462660     x3pa
5     1.815526     x3p.
6    77.071433      x2p
7     5.344820     x2p.
8    14.824743     efg.
9     1.295445      ft.
10    6.649525      ast
11    4.655010      stl
12    2.780759      blk
13   15.277003      tov
14    8.767582       pf
15  115.495140      pts

In [77]:
x_train,x_test,y_train,y_test = train_test_split(X_scaled,y, test_size= 0.25)

In [78]:
knn = KNeighborsClassifier()
knn.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [79]:
knn.score(x_train,y_train)

0.16666666666666666

In [90]:
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_val_score
from sklearn import preprocessing

#read from the csv file and return a Pandas DataFrame.
nba = pd.read_csv('nba_2013.csv')

original_headers = list(nba.columns.values)

# "Position (pos)" is the class attribute we are predicting. 
class_column = 'pts'

feature_columns = ['fg','x3p', 'x2p','orb','drb','ast','stl','blk','tov','pf']


# column selection to split the data into features and class.
nba_feature = nba[feature_columns]
nba_class = nba[class_column]

# normalizing the values in the feature columns.
# When values are scaled between 0 to 1, all of the selected features contribute equally to distance computation
normalized_nba_feature = preprocessing.normalize(nba_feature)

#train_feature, test_feature, train_class, test_class = \
    #train_test_split(normalized_nba_feature, nba_class, stratify=nba_class, \
    #train_size=0.75, test_size=0.25) #75/25 data split
x_train,x_test,y_train,y_test = train_test_split(normalized_nba_feature,nba_class, test_size= 0.25)

training_accuracy = []
test_accuracy = []

#7NN classifier with w=1/d
knn = KNeighborsClassifier(n_neighbors=7, weights='distance',  metric='minkowski', p=1)
knn.fit(x_train, y_train)
prediction = knn.predict(x_test)

In [91]:
knn.score(x_train,y_train)

1.0

In [95]:
prediction

array([ 401,  772,  821,  645,  146,  781,  890,  646,  791, 1227,  159,
        107, 1047,  810, 1068,  159,  821, 1090,  503,  511,  225,  419,
       1071, 1560, 1248,  213,  638,  618,   75,  347,  200, 2112,  520,
        298,   76, 1488, 1118,  249, 1304,   25,  150,  527,  701,  107,
       1249, 2112,  272,   78,  136,  403,  270,  814,  249,  197,  572,
       1542,   73,  136, 2112,  929,  715,  988,  401,  846,   26,   43,
         71,   74,  461,  273,  115,  339,  191, 1167,  530,  529,  132,
        592,   28,  350, 1330, 1118,  525,  893,  527,  530,  856,   74,
        217,  357, 2593,   28,  703,  546,  646, 1542,  911,   76,  347,
        717,  352, 1488, 1291,   65,  846,  339,    0,  665, 1603,   28,
       1873, 1930, 1281,  910,  315,  339,  579, 1068,  150,  339,   97],
      dtype=int64)